using Verse;
using RimWorld;

namespace VanillaMusicExpanded
{
    // CompProperties for albums (the items pawns listen to).
    // IMPORTANT: we set compClass = typeof(CompAlbum) so RimWorld instantiates the right ThingComp.
    public class CompProperties_Album : CompProperties
    {
        // Optional rulepack names for autogenerated names/descriptions
        public string nameMaker;
        public string descriptionMaker;

        // How long a pawn will listen to this album when used in a job
        public int listeningTicks = 1600;

        // How much joy is added per tick while listening
        public float joyAmountPerTick = 0.0001f;

        // Thought gained when finishing
        public ThoughtDef thoughtOnFinish;

        // Optional: store a genre tag for UI/debug/filters
        public string genre;

        public CompProperties_Album()
        {
            compClass = typeof(CompAlbum); // ? REQUIRED: prevents Verse.ThingComp default-ctor crash
        }
    }

    // The runtime component that sits on the album Thing.
    public class CompAlbum : ThingComp
    {
        public CompProperties_Album Props => (CompProperties_Album)props;

        // Explicit default constructor for safety
        public CompAlbum() { }

        public override string CompInspectStringExtra()
        {
            if (Props == null) return null;

            // Build a small inspect string so you can verify values in-game
            string s = $"Duration: {Props.listeningTicks} ticks";
            s += $"\nJoy/tick: {Props.joyAmountPerTick:0.####}";
            if (!string.IsNullOrEmpty(Props.genre))
                s += $"\nGenre: {Props.genre}";
            if (Props.thoughtOnFinish != null)
                s += $"\nOn finish: {Props.thoughtOnFinish.label}";
            return s;
        }
    }
}
